# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: vi
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
  - name: EntitySynonymMapper
#  - name: ResponseSelector
#    epochs: 100
#    retrieval_intent: faq
#    constrain_similarities: true
#  - name: FallbackClassifier
#    threshold: 0.3
#    ambiguity_threshold: 0.1



# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
#  - name: "MemoizationPolicity"
#  - name: "KerasPolicy"
 # - name: "MappingPolicy"
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
  - name: RulePolicy
#    nlu_fallback_threshold: 0.6
#    core_fallback_threshold: 0.3
#    core_fallback_action_name: "action_default_fallback"
 #   enable_fallback_prediction: True

  - name: FallbackPolicy
    nlu_threshold: 0.6
    core_threshold: 0.3
    fallback_action_name: 'utter_fallback'
# This key can be left empty. Policies will then be provided   from a default configuration during training.